name: .NET

on:
  push:
    branches: new-ui
    paths:
      - 'PlagueButtonAPI/**'
      - 'References/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: |
        msbuild.exe PlagueButtonAPI/PlagueButtonAPI.sln /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Normal"
        
    - name: Upload PlagueButtonAPI Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PlagueButtonAPI.dll
        path: PlagueButtonAPI/PlagueButtonAPI/bin/Debug/PlagueButtonAPI.dll
        
    - name: Upload PlagueButtonAPI PDB Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PlagueButtonAPI.pdb
        path: PlagueButtonAPI/PlagueButtonAPI/bin/Debug/PlagueButtonAPI.pdb

    - name: Upload ExampleButtonAPIUsage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ExampleButtonAPIUsage.dll
        path: PlagueButtonAPI/ExampleButtonAPIUsage/bin/Debug/ExampleButtonAPIUsage.dll
      
    - name: Delete Old Releases 
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%y %h:%m %t')"
        
    - name: Create A Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Latest Build [${{ steps.date.outputs.date }}]
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add PlagueButtonAPI.dll To Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PlagueButtonAPI/PlagueButtonAPI/bin/Debug/PlagueButtonAPI.dll
        asset_name: PlagueButtonAPI.dll
        asset_content_type: application/x-msdownload
        
    - name: Add PlagueButtonAPI.dll To Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PlagueButtonAPI/ExampleButtonAPIUsage/bin/Debug/ExampleButtonAPIUsage.dll
        asset_name: ExampleButtonAPIUsage.dll
        asset_content_type: application/x-msdownload
