name: .NET

on:
  push:
    branches: [ beta-ui ]
  pull_request:
    branches: [ beta-ui ]

jobs:
  build:
    defaults:
      run:
        working-directory: PlagueButtonAPI
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
