name: .NET

on:
  push:
    branches: beta-ui

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: |
        msbuild.exe PlagueButtonAPI/PlagueButtonAPI.sln /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Debug"
        
    - uses: actions/upload-artifact@v2
      with:
        name: PlagueButtonAPI.dll
        path: PlagueButtonAPI/bin/Debug/PlagueButtonAPI.dll

    - uses: actions/upload-artifact@v2
      with:
        name: ExampleButtonAPIUsage.dll
        path: ExampleButtonAPIUsage/bin/Debug/ExampleButtonAPIUsage.dll
